Update google-cloudrun-source.yml

diff --git a/.github/workflows/google-cloudrun-source.yml b/.github/workflows/google-cloudrun-source.yml
--- a/.github/workflows/google-cloudrun-source.yml
+++ b/.github/workflows/google-cloudrun-source.yml
@@ -93,8 +93,9 @@ jobs:
           -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
           "$ACTIONS_ID_TOKEN_REQUEST_URL")
         echo "OIDC Token Raw:"
-        echo "$TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d
-
+        echo "$TOKEN"
+        # Extract the payload (2nd part of the JWT) and decode it
+        echo "$TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d || echo "Failed to decode the token payload."
 
     - name: Log OIDC Token
       id: log-token
